on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test this action
        id: hello
        uses: devecorsoft/verify-version@v1
        with:
          current: "1.0.1"
      