on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test this action
        id: hello
        uses: devecorsoft/verify-version@v1
        with:
          current: "1.0.1"
      